
name: example-environment
channels:
  - conda-forge
  - defaults
  - dlr-sc
  - pythonocc
  - oce
dependencies:
  - python=3.6
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pythonocc-core=7.4.0
  - scipy
  - pip
  - pip:
     - "git+https://github.com/daveb-dev/BladeX.git@master"
     - matplotlib
     - nose
     - sip==4.18
     - setuptools
     - coveralls
