name: bladeX_tutorial
channels:
  - conda-forge
  - defaults
  - dlr-sc
  - pythonocc
  - oce
dependencies:
  - python=3.6 
  - pythonocc-core=0.18.1
  - smesh=6.7.5
  - jupyterlab
  - pip
  - pip:
    - git+https://github.com/daveb-dev/BladeX.git@master
