name: bladeX_tutorial
channels:
  - conda-forge
  - defaults
  - dlr-sc
  - pythonocc
  - oce
dependencies:
  - pythonocc-core=7.4.0
  - mesh
  - numpy
  - scipy
  - matplotlib
  - pip
  - nose
  - sip=4.18
  - setuptools
  - coveralls
  - pip:
   - git+https://github.com/daveb-dev/BladeX.git@master
